# 送信系
CAN_ID_EMERGENCY = "101"
CAN_ID_MAP_PRE_INFO = "108"
CAN_ID_MAP_INFO_1 = "109"
CAN_ID_MAP_INFO_2 = "10A"
CAN_ID_ACTION = "10B"
CAN_ID_MANUAL_CTRL = "105"

# 受信系
CAN_ID_FORK_STATUS_1 = "401"
CAN_ID_FORK_STATUS_2 = "402"
CAN_ID_FORK_STATUS_3 = "403"
CAN_ID_FORK_ROAD_CELL = "1F0"
CAN_ID_FORK_LIFT_HEIGHT = "27D"
CAN_ID_FORK_INTERLOCK_1 = "270"
CAN_ID_FORK_INTERLOCK_2 = "27F"
CAN_ID_FORK_ARM_SLANT = "1A0"

# 全体障害通知
CAN_ID_EMERGENCY = "40F"

# ルートタスク
ROUTE_TASK_FORWARD = 0
ROUTE_TASK_REVERSE = 1
ROUTE_TASK_TURN = 2
ROUTE_TASK_LIFTUP = 3
ROUTE_TASK_LIFTUP_WITH_TURN = 4
ROUTE_TASK_LIFTDOWN = 5
ROUTE_TASK_LIFTDOWN_WITH_TURN = 6
ROUTE_TASK_PAUSE = 7
ROUTE_TASK_NOTHING = 255
