# Generated by Django 2.0 on 2017-12-11 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robofork_app', '0001_add_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
