# Generated by Django 2.0 on 2018-03-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robofork_app', '0002_change_date_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('map_image', models.BinaryField(null=True)),
                ('vehicle_initial_positions_json', models.TextField(null=True)),
                ('plc_data_json', models.TextField(null=True)),
                ('fire_doors_json', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=100, null=True)),
                ('extra_info_json', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleOperationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=0)),
                ('route_operation_json', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robofork_app.Location')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='extra_info_json',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicleoperationplan',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robofork_app.Vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robofork_app.VehicleModel'),
        ),
    ]
