# Generated by Django 2.0 on 2018-03-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robofork_app', '0003_auto_20180309_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='vehicle_initial_positions_json',
            new_name='map_information_json',
        ),
        migrations.AddField(
            model_name='vehicleoperationplan',
            name='explain',
            field=models.TextField(null=True),
        ),
    ]
